[project]
name = "hodor-python"
version = "1.1.0"
description = "Python API to access and download the HODOR dataset."
readme = "README.md"
keywords = ["Dataset", "Datasource", "Machine Learning", "Deep Learning", "Data Science", "Underwater Vision", "Underwater Camera", "Marine Science", "Sonar Data", "Stereo Vision", "PANGAEA", "Fishes", "Jellyfishes"]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
maintainers = [
  {name = "Gordon Böer"}
]
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.2",
    "pangaeapy>=1.1.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.scripts]
hodor-python = "hodor_python:main"

[project.urls]
Homepage = "https://github.com/gboeer/hodor_python"
Repository = "https://github.com/gboeer/hodor_python"
Issues = "https://github.com/gboeer/hodor_python/issues"

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[dependency-groups]
dev = [
    "dotenv>=0.9.9",
    "pytest>=8.4.2",
    "ruff>=0.12.12",
]
